# DAY-3 Assignment

Questions 1:
Create a numpy array starting from 2 till 50 with a stepsize of 3.

In [1]:
import numpy as np
arr=np.array([i for i in range(2,51,3)])
print(arr)

[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47 50]


Questions 2:
Accept two lists of 5 elements each from the user.
Convert them to numpy arrays. Concatenate these arrays and print it. Also sort these arrays and print it.

In [14]:
li1=[]
li2=[]
print('Enter the 5 elements of list1')
for i in range(5):
    li1.append(int(input()))
print('Enter the 5 elements of list2')
for j in range(5):
    li2.append(int(input()))
arr1=np.array(li1)
arr2=np.array(li2)
print('concatenate array')
concate_arr=np.concatenate((arr1,arr2))
print(concate_arr)
print('sorted array')
sort_arr=np.sort(arr3)
print(sort_arr)


    
    

Enter the 5 elements of list1
1
2
3
4
5
Enter the 5 elements of list2
0
9
8
7
6
concatenate array
[1 2 3 4 5 0 9 8 7 6]
sorted array
[0 1 2 3 4 5 6 7 8 9]


Questions 3:
Write a code snippet to find the dimensions of a ndarray and its size.

In [30]:
import numpy as np

a_1d = np.arange(3)
a_2d = np.arange(12).reshape((3, 4))
a_3d = np.arange(24).reshape((2, 3, 4))
#how to find the dimentions
print('Dimentions')
print(a_1d.ndim, a_2d.ndim,  a_3d.ndim)
#How to find the shape
print('Shape')
print(a_1d.shape,a_2d.shape,a_3d.shape)
#How to find the size
print('Size')
print(len(a_1d),len(a_2d),len(a_3d))



Dimentions
1 2 3
Shape
(3,) (3, 4) (2, 3, 4)
Size
3 3 2


Questions 4:
How to convert a 1D array into a 2D array? Demonstrate with the help of a code snippet
Hint: np.newaxis, np.expand_dims

In [38]:
A = np.array([1,2,3,4,5,6])
B=np.reshape(A,(2,3))
B

array([[1, 2, 3],
       [4, 5, 6]])

3
